### ISSUE TITLE
Instant View EULA

### ISSUE THREAD

**Issue by tomcounsell** [IntelligentTrading/ui#88]

**Comment by Brbb** [comment]
## EULA acceptance flow
1. user presses START or executes /start
2. telegram-bot send a link to the telegram instant view template handler with a custom address as follow: _t.me/iv?url=https%3A%2F%2Fitt-node-services.herokuapp.com%2Feula%3Fu%3D${chat_id}&rhash=69471435748184_ and gives `chat_id` the user chat_id value.
3. On user's click, node service gets the user chat_id, `POST` on `api/user` with body `{ chat_id: chat_id, eula: 'True' }` and sends a message to the user's chat enabling him to use the /token command
4. user subscribes after `/token <user_token>` checks the EULA field and returns a success message

### TO DOs
- [ ] fix EULA style in terms of margins and alignment
- [ ] integration test with backend
